### ISSUE TITLE
bug: Infinite progress bars on registration screen

### ISSUE THREAD

**Issue by amaskaikin** [IvaTsu/ping-pong-king#69]
![image](https://user-images.githubusercontent.com/10296782/228477445-7a4ccb38-887b-45b0-8eda-a08d99719fec.png)

**Comment by IvaTsu** [comment]
It happens because of this:

```
{gameHistory != null && gameHistory.length > 0 ? (
 ...
 ) : (
            <LoadingSpinner />
          )}
```

Needs to check correctly for the `0` games played.

**Comment by amaskaikin** [comment]
The "Assign" button also has a spinner btw
